name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:

  standard:

    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        example:
          - 14_cmake_findpython

    defaults:
      run:
        shell: bash -l {0}

    name: "${{ matrix.example }} • ${{ matrix.runs-on }}"
    runs-on: ${{ matrix.runs-on }}

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Set conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv

    - name: Configure
      working-directory: ${{ matrix.example }}
      run: cmake -Bbuild -DPython_EXECUTABLE=`which python`

    - name: Compile
      working-directory: ${{ matrix.example }}/build
      run: cmake --build .

    - name: Example
      working-directory: ${{ matrix.example }}/build
      run: |
        cp ../example.py .
        python example.py
